config/routes.rb
Tester::Application.routes.draw do
  

  get "guys/index"
    get "guys/show"

    get "check/index"

    get "winners/index"

    get "home/index"
    get "girls/index"

    get "check/test"
    get "girls/show"
    
    
    match 'check/test' => 'check#test'
    match 'check/remove/:id' => 'check#remove'
    match 'check/addtion/:id' => 'check#addition'
    match 'check/addition' => 'check#addition'
  
  match 'girls' => 'girls#index'
  
  match 'winners' => 'winners#index'
  
  match 'check' => 'check#index'
  
  match 'guy' => 'guys#index'
  match 'guys' => 'guys#index'
  
  
  match "guys/update/:win/:lose" => 'guys#update', :as => 'update_guys'
  
  
  match "girls/update/:win/:lose" => 'girls#update', :as => 'update_girls'
  
  match "girls/update" => 'girls#update'
  
  root :to => "girls#index"
  resources :girls
  resources :guys
  resources :check

end

app/models/addtion.rb
class Addtion < ActiveRecord::Base
end

app/models/girl.rb
class Girl < ActiveRecord::Base
  attr_accessor :expected
  attr_accessible :score, :wins, :picture, :expected, :name, :fb_id, :username
end

app/models/guys.rb
class Guys < ActiveRecord::Base
  attr_accessor :expected
  attr_accessible :score, :wins, :picture, :expected, :name, :fb_id, :username
end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :votes
end

app/models/removal.rb
class Removal < ActiveRecord::Base
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  attr_accessor :girl_votes, :boy_votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  include ApplicationHelper

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  # Render a templated "Not Found" page via app/views/custom_pages/404.html.haml
  def render_404
    render 'custom_pages/404', :status => :not_found, :layout => 'one_column'
    return true
  end

end

app/controllers/check_controller.rb
class CheckController < ApplicationController
  def index
    #puts params[@girl]
    @title = "Check if you are on!"
  end
  
  def test
    @fb =  params[:facebook]
    puts "Test initial: #{@fb}"
    
   @fb.sub!("http://", "")
   @fb.sub!("www.", "")
   @fb.sub!("facebook.com/profile.php?id=", "")
   @fb.sub!("facebook.com/", "")
    #@good = @id.chomp('http://www.facebook.com/')
    
   @girl = Girl.find_by_username(@fb)
   if @girl == nil
     @boy = Guys.find_by_username(@fb)
   end
   #puts "ASDASD"
   #puts @fb
   @arr = []
   
   @name =  URI.escape(@fb, ".")
   @arr << @name
    render 'results'
    #redirect_to check_path(@girl)
  end
  
  def remove
    puts params[:id]
    #Removal.create(:fb_id => params[:id])
    flash[:notice] = "You will be removed! and missed :("
    redirect_to check_path
  end
  
  def addition
    puts params[:id]
    #puts URI.decode(params[:id])
    #Addtion.create(:fb_id => params[:id])
    flash[:notice] = "You will be added!"
    redirect_to check_path
  end
  


end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
  respond_to :html, :js
  def index
    @title = "Women"
    @left, @right = getGirls
  end
  
  def update
     @win = Girl.find(params[:win])
     @lose = Girl.find(params[:lose])
     
     newScore(@win, @lose)
     
     respond_to do |format|
       format.html {redirect_to root_path}
      format.js
     end
  end
  
  def show
    @girl = Girl.find(params[:id])
  end
  
end

app/controllers/goodbye_controller.rb
class GoodbyeController < ApplicationController
  def index
  end

end

app/controllers/guys_controller.rb
class GuysController < ApplicationController
  def index
    @title = "Men"
    @left, @right = getBoys
  end

  def update
    @win = Guys.find(params[:win])
    @lose = Guys.find(params[:lose])
    
    newScore(@win, @lose)
    
    respond_to do |format|
      format.html {redirect_to root_path}
     format.js
    end
  end

  def show
    @guy = Guys.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController
  def index
    @title = "Winners"
    #@girls = Girl.order('score DESC').limit(100).all
    @girls = Girl.paginate(:page => params[:girls_page]).limit(5).order('score DESC')
    #@girls = Girl.paginate(:page => params[:girls_page]).where('girls.username IN(SELECT username FROM girls LIMIT 100)').order('score DESC').per_page(5)
    #@boys = Guys.paginate(:page => params[:boys_page]).limit(5).order('score DESC')
    #@girls = Girl.paginate(:page => params[:girls_page])
    @boys = Guys.paginate(:page => params[:boys_page]).order('score DESC').where('guys.username IN(SELECT username FROM guys LIMIT 100)')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Use within views to set the page's HTML title
  def title(text)
    content_for(:title) { text }
  end

  # Use within views to set the page's HTML meta description
  def description(text)
    content_for(:description) { text }
  end

  # Displays all flash messages in appropriately named divs for easy styling
  def flash_messages
    messages = flash.keys.collect { |key| flash_message(key, flash[key]) }
    content_tag(:div, messages.to_s.html_safe, :id => "flash-messages")
  end

  # Format a single flash message
  def flash_message(type, message)
    content_tag(:div, :class => "flash-message #{type.to_s}") do
      content_tag :p, message
    end
  end
  
  def getGirls
    Girl.order("RANDOM()").limit(2)
  end
  
  def getBoys
    Guys.order("RANDOM()").limit(2)
  end
  
  def newScore(winner, loser)
    
    getExpectedScores(winner, loser)
    puts "Winner score and expected #{winner.score} #{winner.expected}"
    puts "Loser score and expected #{loser.score} #{loser.expected}"
    
    puts "After new rating"

    getNewRating(winner, loser)
    puts "Winner score and expected #{winner.score} #{winner.expected}"
    puts "Loser score and expected #{loser.score} #{loser.expected}"
      
  end
  
  def getExpectedScores(player1, player2)
    if (player1.score > player2.score)
      higher_rating_b = player1
      lower_rating_a = player2
    else
      higher_rating_b = player2
      lower_rating_a = player1
    end

    d = higher_rating_b.score - lower_rating_a.score
    a = 205 - (lower_rating_a.score.fdiv(20))

    lower_rating_a.expected = 1.fdiv(Math::E**(d.fdiv(a)) +1)
    higher_rating_b.expected = 1 - lower_rating_a.expected
  end
  
  def getK(player)
    rate = player.score
    122 - 6 * (rate.fdiv(100)) + (((rate.fdiv(100)**2)/15))
  end

  def getNewRating(winner, loser)
    winner_score = winner.score + getK(winner) * (1 - winner.expected)
    loser_score = loser.score + getK(loser) * (0-loser.expected)
    winner.update_attributes(:score => winner_score)
    loser.update_attributes(:score => loser_score)
  end
  
  # def updateGirlsScores(win, lose)
  #   puts win
  #   puts lose
  #   winExpected = getExpectedChance(win.score, lose.score)
  #   loseExpected = getExpectedChance(lose.score, win.score)
  #   
  #   diff = (win.score - lose.score).abs
  #   
  #   win.update_attributes(:score => win.score + 1)
  #   win.update_attributes(:wins => win.wins + 1)
  #   
  #   if (diff >= 40 && (winExpected < 0.5 || loseExpected >= 0.5))
  #     win.update_attributes(:score => adjustRate(win.score, winExpected, 1))
  #     lose.update_attributes(:score => adjustRate(lose.score, loseExpected, 0))
  #   end
  # end
  # 
  # def getExpectedChance(score1, score2)
  #  (1.fdiv((1+(10**((score2-score1).fdiv(400))))))
  # end
  # 
  # def adjustRate(ra, ea, sa)
  #   if (ra < 500)
  #     k = 32
  #   elsif (ra < 1000)
  #     k = 24
  #   else
  #     k = 16
  #   end
  # 
  #  return ra + (k*(sa - ea))
  # end

end

app/helpers/check_helper.rb
module CheckHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
  def display_girl_image(person)
    "https://s3.amazonaws.com/sadf/girls/girls/" + person.picture
  end
end

app/helpers/goodbye_helper.rb
module GoodbyeHelper
end

app/helpers/guys_helper.rb
module GuysHelper
  def display_image(person)
   "https://s3.amazonaws.com/sadf/girls/guys/" + person.picture
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
  def display_girl_image(person)
    "https://s3.amazonaws.com/sadf/girls/girls/" + person.picture
  end
  
  def display_guy_image(person)
    "https://s3.amazonaws.com/sadf/girls/guys/" + person.picture
  end
end

app/views/check/index.html.erb
<div id='check'>
	<div id="flash-messages">
	<% if flash[:warning] or flash[:notice] %>
	  <div class="notice" <% if flash[:warning] %>class="warning"<% end %>>
	    <%= flash[:warning] || flash[:notice] %>
	  </div>
	<% end %>
 	</div>
	
	
	<% form_tag 'check/test' do %>
		<%= label_tag 'Enter your Facebook URL here' %>
		<%= text_field_tag 'facebook', '', :size=> 75 %>
		
		<%= submit_tag 'Check' %>
	<% end -%>
</div>

app/views/check/results.html.erb
<script>
$(function() {
	$("#remove-button").click(function() {
		alert("You will be removed");
		$("#remove-button").hide();
	});
	
	$("#add-button").click(function() {
		alert("You will be added!");
		$("#add-button").hide();
	});
});
</script>

<div id='check'>
	<% puts "In view: #{@name}" %>
	<% if @girl != nil%>
		Welcome <%= @girl.name %>: <br />
		Fb ID: <%= @girl.fb_id %> <br />
		Score: <%= @girl.score %> <br />
		Picture: <%= link_to(image_tag("https://s3.amazonaws.com/sadf/girls/girls/" + @girl.picture, 
												:height => '150'), @girl) %> <br /> <br />
		
		<%= button_to('Click here if you would like to remove yourself', 'index',
						:method => Removal.create(:fb_id => URI.decode(@girl.username)), :remote => true,
															:id => 'remove-button') %>
															sdfsd
	
	<% elsif @boy != nil %>
		Welcome <%= @boy.name %><br />
		FB ID: <%= @boy.fb_id %><br />
		Score: <%= @boy.score %><br />
		Picture: <%= link_to(image_tag("https://s3.amazonaws.com/sadf/girls/guys/" + @boy.picture,
															:height => '150'), @boy) %><br /><br />
		<%= button_to('Click here if you would like to remove yourself', 'index',
					:method => Removal.create(:fb_id => URI.decode(@boy.username)), :remote=> true,
																:id => 'remove-button')%>
																
	
	
	
	<% elsif @girl == nil || @boy == nil%>
		You were not found :( <br /><br />
		<%= button_to('Click here to add yourself', 'addition',
		 :method => Addtion.create(:fb_id=>URI.decode(@name)),
								:remote => true, :id => 'add-button')%>
	<% end %>
	
	<br /> <br />
	
	<%= link_to "Check Another Person", check_path %>
</div>

app/views/girls/_vote.html.erb
	<div id='message'>
	Click or use the <strong>arrow keys on the keyboard</strong> to indicate who is more attractive. <br />
	If there are multiple people in the picture, just vote for the better picture! ✠
	</div>
	<div id='photos'>

		
	<div id='left'>
		<%= link_to image_tag(display_girl_image(@left), :width => 300), 
										update_girls_path(@left, @right),
		 								:method => :post, :remote => true, 
										:id=>'leftimage' %>
	</div>
	<div id='middle'>
		OR
	</div>

	<div id='right'>

		<%= link_to image_tag(display_girl_image(@right), :width => 300), 
										 update_girls_path(@right, @left),
										  :method => :post, 
										  :remote => true,:accesskey => "r",
										  :id=>'rightimage'%>
		<div id='orange-image'>								
			<%= image_tag("orange-words.png")%>
		</div>
	</div>
	</div>

app/views/girls/index.html.erb
<script>
$(function() {
	$(document).keyup(function(e){
	    if (e.keyCode == 37) { 
		var left = $("#leftimage");
		var url = left.attr('href');
	 $.ajax({
		type: 'PUT',
	 	url:url,
		dataType: 'script'
	 });
		       return false;
	    }
	
		else if (e.keyCode == 39) {
			var right = $("#rightimage");
			var url = right.attr("href");
			
			$.ajax({
			type: 'PUT',
		 	url:url,
			dataType: 'script'
		 });
		return false;
		}
	});
});
</script>
<%= render('layouts/menwomen')%>

<div class='vote' id='vote'>
<%= render('vote') %>
</div>

app/views/girls/show.html.erb
<div id='show-girl'>
	Score: <%= @girl.score %>
	<br /><br />	
	<%= image_tag(display_girl_image(@girl), :width => 300) %>
</div>

app/views/girls/update.js.erb
<% @left, @right = getGirls%>

$("#vote").html("<%= escape_javascript(render('girls/vote')) %>")

app/views/goodbye/index.html.erb
<h1>Greetings!</h1>
<br />
<p>I will be disabling URhotURnot.org.</p>
<p>Glad most of you enjoyed it! Sorry to the others :(</p>
<p>If you want to contact me you can email me at urhoturnot@gmail.com</p>
<br />
<p>Have a good week everyone!</p>

<br /><br />
<p>Fun fact: During the couple days the site was live on the weekend it received about <b>~90,000 page views</b>! Crazy stuff.</p>

app/views/guys/_vote.html.erb
<div id='message'>
Click or use the <strong>arrow keys on the keyboard</strong> to indicate who is more attractive. <br />
If there are multiple people in the picture, just vote for the better picture! ✠
</div>
<div id='photos'>

	
<div id='left'>
	<%= link_to image_tag(display_image(@left), :width=>300), 
									update_guys_path(@left, @right),
	 								:method => :post, :remote => true, 
									:id=>'leftimage' %>
</div>
<div id='middle'>
OR
	
	<br />
	<br />
</div>

<div id='right'>

	<%= link_to image_tag(display_image(@right), :width=>300), 
									 update_guys_path(@right, @left),
									  :method => :post, 
									  :remote => true,:accesskey => "r",
									  :id=>'rightimage'%>
	<div id='orange-image'>								
		<%= image_tag("orange-words.png")%>
	</div>
</div>
</div>

app/views/guys/index.html.erb
<script>
$(function() {
	$(document).keyup(function(e){
	    if (e.keyCode == 37) { 
		var left = $("#leftimage");
		var url = left.attr('href');
	 $.ajax({
		type: 'PUT',
	 	url:url,
		dataType: 'script'
	 });
		       return false;
	    }
	
		else if (e.keyCode == 39) {
			var right = $("#rightimage");
			var url = right.attr("href");
			
			$.ajax({
			type: 'PUT',
		 	url:url,
			dataType: 'script'
		 });
		return false;
		}
	});
});
</script>
<%= render('layouts/menwomen')%>

<div class='vote' id='vote'>
<%= render('vote') %>
</div>

app/views/guys/show.html.erb
<div id='show-girl'>
	Score: <%= @guy.score %>
	<br /><br />
	
	<%= image_tag("https://s3.amazonaws.com/sadf/girls/guys/"+@guy.picture, :width => 300) %>
</div>

app/views/guys/update.js.erb
<% @left, @right = getBoys %>

$("#vote").html("<%= escape_javascript(render('guys/vote')) %>")

app/views/layouts/_footer.html.erb
✠ Sorry for the small pictures. All of the images are from public Facebook profiles who (hopefully) attend the University of Regina. The size of images is the largest that can be obtained with the Facebook API. <br />

★ This site is not affiliated with the University of Regina in any way. We do, however, make use of their corny habit of using UR in replace of you're. <br />

⋈ This site is just for fun! 

app/views/layouts/_header.html.erb
<div class='top'>
	<h1><%= link_to_unless_current 'URhotURnot', root_path %></h1>
	<h8><font color='red'>Removed the people that requested. If you requested and are still on let me know. If you never requested and were removed, do the same  </font></h8>
	<h3>University of Regina Hot or Not: &nbsp <%= link_to_unless_current 'View Winners', winners_path %> &nbsp  | &nbsp  
		<%= link_to_unless_current "Check if UR a contestant (add/remove)", check_path %> </h3> 
	<div class="side">
		 Created by Jonovono <br />
		Email: urhoturnot@gmail.com
	</div>
</div>

app/views/layouts/_menwomen.html.erb
<div class='men-women'>
	<%= link_to_unless_current "Men", guys_path %> or 
	<%= link_to_unless_current "Women", root_path %>
	<% if params[:controller] == "guys" %>
		<%= button_to "SKIP", guys_path %>
	<% else %>
		<%= button_to "SKIP", root_path %>
	<% end %>	
</div>

app/views/layouts/_sidebar.html.erb
<div id='sidebar'>
	<h3>University of Regina Hot or Not:</h3><br /><br /> View the Top Rated list<br /> Check if you are on list (and add/remove yourself)
</div>

app/views/layouts/application.html.erb
<!doctype html>
<%-# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ %>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">


<link href="tmp/stylesheets/screen.css" rel="stylesheet" type="text/css" />

  <%-# Always force latest IE rendering engine. Remove this if you use the .htaccess fix %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%-# Use content_for :title in views to set page title %>
  <title>
    URhotURnot: University of Regina Hot or Not |  <%= @title %>
  </title>

  <%-# Use content_for :description in views to set page description %>
  <meta name='description' content="<%= content_for?(:description) ? yield(:description) : 'Generic page description.' %>">
  <meta name="author" content="">

  <%-# Mobile viewport optimized: j.mp/bplateviewport %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%-# Required for Rails3 %>
  <%= csrf_meta_tag %>
 
  <%-# Boilerplate CSS files %>
  <%= stylesheet_link_tag 'html5-boilerplate', :media => 'all' %>
  <%= stylesheet_link_tag 'html5-boilerplate-handheld', :media => 'handheld' %>

  <%= stylesheet_link_tag 'page' %>

  <% if false %>
  <%-# Application CSS files (from SASS sources in app/stylesheets) %>
  <%= stylesheet_link_tag 'compiled/screen', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'compiled/print', :media => 'print' %>
  <%= stylesheet_link_tag 'compiled/handheld', :media => 'handheld' %>
  <% end %>

  <%-# Use content_for :stylesheets in views to include custom stylesheets %>
  <%= yield :stylesheets %>
  
  <%-# All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detection %>
  <%= javascript_include_tag 'modernizr-1.7.min.js' %>
  <%= javascript_include_tag :defaults, 'application' %>
</head>

<body>


<div id='container'>
    <header id='page-header'>
	<%= render('layouts/header') %>
    </header>
      <%= yield %>
	<footer id='page-footer'>
		<%= render('layouts/footer') %>
	</footer>
</div>

  <!-- JavaScript at the bottom for fast page loading -->

  <%-# Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js"></script>
  <script>window.jQuery || document.write("<script src='javascripts/jquery-1.5.1.min.js'>\x3C/script>")</script>

  <%-# Application javascripts %>
  <%= javascript_include_tag 'rails', 'application' %>

  <%-# Use content_for :scripts in views to include custom scripts %>
  <%= yield :scripts %>

  <%-# BelatedPNG adds some PNG support to IE6 %>
  <!--[if lt IE 7 ]>
    <script src="javascripts/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix("img, .png_bg"); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
  <![endif]-->
<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=7248908; 
var sc_invisible=1; 
var sc_security="f3c25e1d"; 
</script>

<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
class="statcounter"><a title="counter for vBulletin"
href="http://statcounter.com/vbulletin/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/7248908/0/f3c25e1d/1/"
alt="counter for vBulletin" ></a></div></noscript>
<!-- End of StatCounter Code -->

</body>
</html>

app/views/shared/_error_messages.html.haml
-# Use inside forms like this:
-#
-# = form_for @user do |f|
-#   = render '/shared/error_messages', :target => @user
-#
-# See http://asciicasts.com/episodes/211-validations-in-rails-3

- if target.errors.any?
  #errorExplanation
    %h2
      = pluralize(target.errors.count, "error")
      prohibited this record from being saved:
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/winners/index.html.erb
<div class='both-sex'>

<div id='top-girls'>
	<h1>Top 100 Women</h1>
	<% @girls.each do |girl| %>
	<%= link_to (image_tag(display_girl_image(girl), :height => 70)), girl %>
		<%= girl.score %> <br />
	<% end %>
	
	<%= will_paginate @girls,:param_name => 'girls_page' %>
</div>

<div id='top-boys'>
	<h1>Top 100 Men</h1>
	<% @boys.each do |boy| %>
	<%= link_to (image_tag(display_guy_image(boy), :height => 70)), boy %>
		<%= boy.score %> <br />
	<% end %>
	
	<%= will_paginate @boys, :param_name => 'boys_page' %>
	
</div>

</div>